# docker/Dockerfile.admin
FROM node:18-bullseye AS builder

RUN apt-get update && apt-get install -y bash && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ../frontend-admin-panel/package*.json ./
RUN npm install --verbose
COPY ../frontend-admin-panel/ .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]